# Generated by Django 2.2 on 2019-04-08 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190408_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('SO', 'Not available')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
